### ISSUE TITLE
Missing .gitignore files in generated project

### ISSUE THREAD

**Issue by antonjahn** [A-Maiorov/create-lit-pwa#2]
Hi, this is a great starter project, it took me litterally minutes to get a good starting point including testing. Well done!

However, there is a problem which you may want to consider.

### Problem
After running `npm init lit-pwa@latest` there is no .gitignore in the populated folder.

### Root cause
When running the script directly from this repository (git clone, then just node main.js)
then the generated folder contains the .gitignore file correctly.

However when I look at the content of the npm package: the .gitignore files are missing from the package.

So to me it seems that the npm package & publish step on your side somehow drops the .gitignore files from
templates/basic/.gitignore.

### Solution proposal

Based on a quick search it seems that npm would use a dedicated .npmignore file it were present. In case the file does not exist, npm assumes .npmignore = .gitignore. However, I am no npm publisher, so I might have missed something.

https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package

I assume that adding the .npmignore file should solve this. 

Hope that helps, would be great if you have time to fix it, or if somebody with a little more npm experience can send a pull request to fix.

**Comment by A-Maiorov** [comment]
Hey @tonjy, thanks for the feedback! I've just published new version with a fix for this issue. Feel free to run `npm init lit-pwa@latest` and `.gitignore` will be added to the folder.

**Comment by antonjahn** [comment]
Yes, your solution works thanks for providing this starter & the quick response!
